spring:
  application:
    name: AppointmentService
  config:
    import:
      optional:
        configserver:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  eureka:
    client:
      enabled: false
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/appointment_db
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8081


