spring:
  application:
    name: Appointment-Service

  cloud:
    config:
      enabled: false
    discovery:
      enabled: true

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/appointment_db
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: bcb8bb50e0713d
    password: b8389533f4af90
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    enabled: true

    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:

server:
  port: 8085


