spring:
  application:
    name: Admin-Service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true

eureka:
  client:
    enabled: true

    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:

server:
  port: 8083
