spring:
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://localhost:9999
    activate:
      on-profile: default
  main:
    allow-bean-definition-overriding: true
server:
  port: 8888

jwt:
  secret: MySuperSecretKey1234567890
