spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
#    gateway:
#      routes:
#        - id: r1
#          uri: lb://USERSERVICE
#          predicates:
#            - Path=/api/user/** ,/api/doctor/** ,/api/admin/**
    discovery:
      enabled: true
eureka:
  client:
    enabled: true

    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8888
