spring:
  application:
    name: config-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: file:///C:/Users/abdel/Desktop/intelij/Appointment_Medical/config-repository
    discovery:
      enabled: true

eureka:
  client:
    enabled: true

    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

server:
  port: 9999
