spring:
  application:
    name: admin-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt:
  secret: MySuperSecretKey1234567890

server:
  port: 8083